In [1]:
import pandas as pd

df = pd.read_csv("treatment.csv")
df["recovery_in_3_days"] = df["recovery_in_3_days"].map({0:"No",1:"Yes"})
df

   treatment_category recovery_in_3_days
0                   A                Yes
1                   A                 No
2                   B                 No
3                   B                 No
4                   A                Yes
5                   B                Yes
6                   B                Yes
7                   C                Yes
8                   A                Yes
9                   C                Yes
10                  C                 No
11                  B                Yes
12                  B                Yes
13                  B                 No
14                  C                Yes
15                  A                 No
16                  B                 No
17                  B                 No
18                  A                Yes
19                  B                Yes
20                  B                Yes
21                  A                Yes
22                  A                 No
23                  B                 No
24                  A                Yes
25                  B                Yes
26                  B                Yes
27                  B                Yes
28                  B                 No
29                  B                 No
30                  B                Yes
31                  B                Yes
32                  B                Yes
33                  B                 No
34                  B                 No
35                  B                Yes
36                  B                Yes
37                  B                Yes
38                  B                 No
39                  B                 No

In [2]:
gb= (
    df
    .groupby(["treatment_category","recovery_in_3_days"],as_index=False)
    .agg(count=("treatment_category","count"))
)
gb

  treatment_category recovery_in_3_days  count
0                  A                 No      3
1                  A                Yes      6
2                  B                 No     12
3                  B                Yes     15
4                  C                 No      1
5                  C                Yes      3

In [3]:
gb.pivot_table(index=["treatment_category"]
               ,columns=["recovery_in_3_days"]
               ,values='count'
               ,aggfunc="sum"
               , margins=True
              )

recovery_in_3_days  No  Yes  All
treatment_category
A                    3    6    9
B                   12   15   27
C                    1    3    4
All                 16   24   40