# Statistiques descriptives

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

1. **Statistique descriptive** : 
    1. But  
        - Résume et décrit les données (via des mesures et des graphiques visuels)  
        - Permet de détecter de potentiel "outlier" (valeurs aberrantes)
        - Prépare aux "data cleaning"
        - Prépare aux modèles inférentiels

    2. Comment mettre en nombres :  
        -  "chiffres"/"données"/"information" = statistiques  
        - mesure de tendance centrale  
        - mesure de dispersion/variation  

    3. Distributions
        - fréquences et effectifs
        - graphiques: barplot, histogrammes, nuage de points, etc.
        - représentation graphique des statistiques "tabulaires"/"chiffres"

2. ***Statistique descriptive univariée*** fournit les outils statistiques pour organiser, présenter et synthétiser l’information issue de l’analyse d’une variable indépendamment des autres
    -  nominale
        - mode, fréquences
        - pie, bar
    -  ordinale
        - mode, médiane & IQR, fréquences
        - pie, bar, boxplot
    -  discrète
        - mode, médiane & IQR, moyenne et écart-type, fréquences(*)
        - histogramme, boxplot, ecdf
    -  continue
        - médiane & IQR, moyenne et écart-type, fréquence(*)
        - histogramme, boxplot, ecdf


3. ***Statistique descriptive bivariée*** a pour objet d’étudier conjointement deux variables X et Y sur une même population
    - catégories vs catégories
        - fréquences, mode
    - catégories vs numérique
        - comme numérique, mais ventilation par catégories
    - numérique vs numérique
        - covariance, corrélation
        - nuage de points

    
4. ***Statistique descriptive multivariée*** vise à étudier plusieurs variables simultanément  
    - pairplot,
    - joinplot,
    - violinplot,
    - groupby,
    - ...

### les données pour l'illustration

In [2]:
d1 = pd.read_csv("notes_V2.csv")
d1["id"] = d1.index
display(d1.head())
d1.info()

   index  math  eng    group gender  id
0      0   5.2  6.8     lang      F   0
1      1   4.6  7.1     lang      M   1
2      2   5.4  8.0     lang      F   2
3      3   4.7  8.1     lang      M   3
4      4   7.6  6.0  science      M   4

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   index   1000 non-null   int64
 1   math    1000 non-null   float64
 2   eng     1000 non-null   float64
 3   group   1000 non-null   object
 4   gender  1000 non-null   object
 5   id      1000 non-null   int64
dtypes: float64(2), int64(2), object(2)
memory usage: 47.0+ KB

# Tendance centrale
- Où se situe le centre des données ?
- Quelle est la valeur la plus représentative du dataset?

### moyenne (arithmétique)
- applicable pour les numériques (discrète et continue)
- EN: mean, average

$ \text{mean}(X) = \bar{x} = \frac{\sum_{i=1}^{N} x_i}{N} = \frac{1}{N} \left(x_1 + x_2 + ... + x_N\right)
$

ce n'est pas une mesure robuste, car elle est sensible aux valeurs extrêmes


Dans les statistiques inférentielles, on va utiliser le symbole grec "mu" $\mu$ pour désigner la moyenne de la population (la valeur fondamentale/théorique). En lien avec cette valeur, on peut retrouver l'expression suivante:

$\hat{\mu} = \bar{x} = \frac{\sum_{i=1}^{N} x_i}{N} $  

Cela signifie qu'on peut estimer (=une approximation maitrisée de) cette valeur $\mu$ avec la moyenne $\bar{x}$.

![](repos/mean.png)

In [3]:
list_ = [0,1,1,2,3,5,8]
list_extr = list_ + [100]

print(np.mean(list_))
print(np.mean(list_extr))

2.857142857142857
15.0

In [4]:
avg_math = d1["math"].mean()
display(avg_math)

np.float64(6.54)

### Mediane
- applicable pour les données ordinales et numériques
- EN: median, 2nd quartile, 50-percentile

On trie les données (d'une manière croissante), et on prend la valeur du milieu de cette liste trié.

- si elle est de longueur impaire -> pas d'ambiguïté sur la valeur du milieu
- si la liste est de longueur paire -> la moyenne des 2 valeur du milieu

c'est une mesure robuste:
- elle n'est pas sensible aux valeurs extrêmes

![](repos/median.png)

In [5]:
list_sorted = [0,1,1,2,3,5,8]
median = list_sorted[int(len(list_sorted)/2)]
median

2

In [6]:
list_ext_sorted = list_extr.copy()
low = int(len(list_ext_sorted)/2)-1
high = int(len(list_ext_sorted)/2)
median = 0.5*(list_ext_sorted[low]+list_ext_sorted[high])
print(low)
print(high)
median

3
4

2.5

In [7]:
median = d1.math.median()
median

6.4

### Mode
- applicable pour les catégories (nominales, ordinales) est les discrètes
- EN: mode

c'est la valeur qui revient le plus souvent


<img src="repos/mode.png" alt="drawing" style="width:300px;"/>

In [8]:
list_sorted = [0,1,1,2,3,5,8]
mode = 1

In [9]:
d1["group"].mode()

0       lang
1    science
Name: group, dtype: object


### moyenne (arithmétique) pondérée
$\bar{x} = \frac{\sum_{i=1}^{N} w_i \cdot x_i}{\sum_{i=1}^{N} w_i}$

chaque valeur possible $x_i$ a un poids $w_i$, on tient compte de ce poids dans la moyenne:
- à noter que quand tous les poids sont identiques <br>
( par  exemple $w_i=1$ ) ,<br> on retrouve la moyenne (arithmétique)

exemple:
- note globale pour un élève est la moyenne des scores d'examens pondérés par le nombre d'heures par semaine des cours
    - Dans une classe de secondaire 'math forte' : l'examen de mathématique compte pour 6, alors que religion que pour 1.

In [3]:
## alice est dans math-forte
score_alice = {"math":16,"francais":15,"religion":12,"geo":10} ## score sur 20

nbre_heures_dans_semaine = {"math":6,"francais":5,"religion":1,"geo":2}

somme_heures = 0
somme_pondere = 0
for cours in score_alice.keys():
    score_cours = score_alice[cours]
    nbr_h_cours = nbre_heures_dans_semaine[cours]
    somme_pondere += score_cours*nbr_h_cours
    somme_heures += nbr_h_cours

moyenne_pond = somme_pondere/somme_heures

print(moyenne_pond)

14.5

In [5]:
sum(score_alice.values())/len(score_alice)

13.25


### (BONUS) moyenne (arithmétique) tronquée
$\bar{x}_{tr} = \frac{\sum_{i=p}^{N-p} x_i}{N-2p}$

on élimine un nombre $p$ de valeurs les plus basses et plus élevées avant de faire la moyenne

### (BONUS) autres moyenne que l'arithmétique


Le plus classique, c'est évidemment la moyenne arithmétique:

celle-ci a du sens que quand la somme des éléments est pertinente pour un total:
exemple avec des cordes:
 - j'ai des cordes avec des longueurs différentes
     - $L_n$
 - j'ai 10 cordes
     - $N = 10$
 - quand je les mets bout à bout, j'obtiens une longueur totale de 20m
     - $\sum_n L_n =L_{tot} = 20 $ 
 - la longeur de corde représentative de l'ensemble est 2
     - $\frac{L_{tot}}{N} = 2$
 - ici, pour calculer le total, j'ai eu besoin de l'addition :
     - j'utilise donc la moyenne arithmétique pour la moyenne 

À noter que ce n'est pas toujours l'addition qui est pertinente pour calculer un total.
En fonction de l'opération (addition,multiplication,...) pertinente pour le total, on utilise une moyenne différente comme valeur représentative.

#### [moyenne géométrique](https://en.wikipedia.org/wiki/Geometric_mean)

La moyenne géométrique est appropriée quand le total est issu d'une multiplication de valeurs.

#### [moyenne harmonique](https://en.wikipedia.org/wiki/Harmonic_mean)

La moyenne harmonique est appropriée quand on veut calculer une 'fréquence'/ratio/vitesse

# Mesures de dispersion
- dispersion=variation
- quelle est la variation des données ?

Les mesures de tendances centrales ne sont pas du tout suffisantes pour bien résumer les data en statistiques !

In [10]:
print(list_)
list_highvar = [-100,2,4,8,100]
print(list_highvar)

print('-'*50)

print(np.mean(list_))
print(np.mean(list_highvar)) ## moyenne similaire

[0, 1, 1, 2, 3, 5, 8]
[-100, 2, 4, 8, 100]
--------------------------------------------------
2.857142857142857
2.8

### Amplitude
- Amplitude ou Étendue
- EN: range
- applicable quand médiane est applicable

c'est la distance entre la valeur maximum et minimum 

$\text{range}(X) = \max(X) - \min(X)$

![](repos/range.png)

In [11]:
print(np.max(list_) - np.min(list_))
print(np.max(list_highvar) - np.min(list_highvar))

8
200

### Déviation absolue moyenne
- mean absolute deviation
- applicable quand la moyenne est applicable

cette mesure est moins sensible aux valeurs extrêmes

$ \text{mad}(X) = \frac{\sum_{i=1}^{N} |x_i-\bar{x}|}{N}$

In [12]:
(d1.math - d1.math.mean()).abs().mean()

np.float64(1.2151599999999998)

In [13]:
m_ = np.mean(list_)
np.mean([np.abs(x-m_) for x in list_])

np.float64(2.1224489795918364)

In [14]:
m_ = np.mean(list_highvar)
np.mean([np.abs(x-m_) for x in list_highvar])

np.float64(41.44)

### Variance et écart-type
- variance and standard deviation
- applicable quand la moyenne est applicable

cette valeur est très sensible aux valeurs extrêmes

$\text{var}_\text{population}(X) = \sigma^2= \frac{\sum_{i=1}^{N} (x_i - \mu)^2}{N}$

$\text{var}_\text{sample}(X)= s^2 = \frac{\sum_{i=1}^{N} (x_i - \bar{x})^2}{N-1}$



[facteur de correction](https://en.wikipedia.org/wiki/Bessel%27s_correction) $N-1$ de Bessel :
- à utiliser quand on calcule la variance en utilisant la moyenne observée $\bar{x}$ d'un échantillon (=une estimation/observé), à la place de la vraie moyenne $\mu$ (= valeur fondamentale/théorique de la population).

Cette correction n'est vraiment importante que quand on a peu de données (<20), donc en pratique (commercial/industriel N>10000) cette nuance n'a pas d'impact significatif.

On reviendra sur les différences et les liens probabilités (=inférentiel) et statistiques (=descriptive).

Notez que la formule/définition correspond à la ***moyenne des carrés des distances*** Euclidienne entre:
- les données $x_i$
- et la moyenne (de population/théorique) $\mu$ :

$\text{var}_\text{population}(X)$   
    $ = \frac{1}{N} ||X - \mu||^2 $  
    $ = \frac{1}{N} (X-\mu)^T \cdot (X-\mu) $  
    $ = \frac{1}{N}\begin{bmatrix}
    (x_1 - \mu) & (x_2 - \mu) & ... & (x_N - \mu)
\end{bmatrix} \cdot 
\begin{bmatrix}
    (x_1 - \mu) \\ (x_2 - \mu) \\ ... \\ (x_N - \mu)
\end{bmatrix} $  
    $= \frac{\sum_{i=1}^{N} (x_i - \mu)^2}{N}$


<img src="repos/variance.png" alt="drawing" style="width:200px;"/>

In [15]:
print(np.var(list_))
print(np.var(list_highvar))

6.693877551020407
4008.9600000000005

Si les données ont comme unité "mètre" "$m$", la variance a des unités "mètre carré" "$m^2$".
Ceci complique l'interprétation des résultats, car peu intuitif. C'est pour cela qu'on préfèrera utiliser les écarts-types (standard déviation).



$\text{std}_\text{pop}(X) = \sigma = \sqrt{\frac{\sum_{i=1}^{N} (x_i - \mu)^2}{N}} = \sqrt{\text{var}_\text{pop}}$ 

$\text{std}_\text{sample}(X) = s = \sqrt{\frac{\sum_{i=1}^{N} (x_i - \bar{x})^2}{N-1}} = \sqrt{\text{var}_\text{sample}}$ (*)

(*): une correction de 1.5 au lieu de 1 serait plus [exacte](https://en.wikipedia.org/wiki/Unbiased_estimation_of_standard_deviation), pour avoir une estimation non biaisée de l'écart-type fondamental/théorique "$\sigma$"

Comme pour la variance, en pratique, les nuance entre "$\sigma$" et "$s$" sont négligeable ($N>1000$). 

![](repos/std.png)

In [16]:
print(np.std(list_,ddof=0))
print(np.std(list_highvar, ddof=0))

2.58725289661069
63.31634859971002

### Quartiles et écart interquartile
- EN: quartiles and interquartile range (IQR)
- applicable quand médiane est applicable

Q1 = la médiane entre :
- le minimum
- et la médiane

Q2 = la médiane

Q3 = la médiane entre :
- la médiane
- et le maximum

Par construction/définition :
- on a 25% du nombre des données entre (min,Q1),(Q1,Q2),(Q2,Q3),(Q3,max)

- on a 75% des valeurs qui se trouve entre le Q1 et max
- on a 50% des valeurs entre Q1 et Q3




IQR c'est la distance entre Q3 et Q1

on a des définitions similaires avec 
- decile = tranche de  10%
- pourcentile = tranche de 1%
- 
<img src="repos/IQR.png" alt="drawing" style="width:300px;"/>

In [17]:
Q1 = d1.math.quantile(q=0.25)
Q2 = d1.math.quantile(q=0.5)
Q3 = d1.math.quantile(q=0.75)

print(Q2 == d1.math.median())
print("-"*50)
print(Q1,Q2,Q3)

True
--------------------------------------------------
5.4 6.4 7.6

In [18]:
IQR = Q3-Q1
print(IQR)

2.1999999999999993


### Pour une distribution normale
- =courbe de Gauss, (distribution paramétrique)
- EN: normal distribution, Gauss curve

**Règle de J.Tuckey**: une donnée peut être appelée valeur (potentiellement) aberrante/extrême si elle s'écarte d'une
distance d'au moins 1,5xIQR au-dessus du Q3 ou en dessous du Q1.

**Cela permet de separer/identifier les données "standards" des données potentiellement "aberants"**, et de faire une analyse générale/global pour l'un et sur mesure pour l'autre. 

<img src="repos/boxplot-gauss.png" alt="drawing" style="width:500px;"/>

### Covariance
- EN: Covariance
- applicable quand la moyenne est applicable (sur les deux variables)
- c'est une extension de la variance
- permet de faire une analyse sur 2 variables (=bivarié)
C'est une mesure qui quantifie comment deux variables $X$ et $Y$ varient ensemble quand on parcours toutes les données d'un dataset


$\text{covar}_\text{pop}(X,Y) = \frac{\sum_{i=1}^{N} (x_i - \mu_x)\cdot (y_i - \mu_y)}{N}$

$\text{covar}_\text{sample}(X,Y) = \frac{\sum_{i=1}^{N} (x_i - \bar{x})\cdot (y_i - \bar{y})}{N-1}$

### Coefficient de corrélation 
- EN: correlation coefficient
- permet de faire une analyse sur 2 variables (=bivarié)

#### [Pearson](https://en.wikipedia.org/wiki/Pearson_correlation_coefficient)
- applicable quand la moyenne est applicable aux deux variables $X$ et $Y$
- ceci représente la "force" d'association (linéaire) entre deux variables:
    - exemple : quand je fait varier les valeurs de $X$  d'une valeur basse à haute, est-ce que les valeurs de la variable $Y$ ont tendance à changer avec les mêmes directions : également un changement de bas à haut ?
        - si $\rho \approx 1$: elles vont dans le même sens 
        - si $\rho \approx -1$: dans le sens opposé
        - si $\rho \approx 0$: le changement d'une variable n'impacte pas l'autre

$\rho(X,Y) = \frac{\text{covar}(X,Y)}{\text{std}(X) \cdot \text{std}(Y)} $

$-1 \leq \rho(X,Y) \leq 1$

In [19]:
d1[["math","eng"]].corr(method='pearson')

          math       eng
math  1.000000 -0.339452
eng  -0.339452  1.000000

#### [Spearman](https://en.wikipedia.org/wiki/Spearman%27s_rank_correlation_coefficient)
- applicable quand la médiane est applicable aux deux variables $X$ et $Y$
- ceci représente la "force" d'association (de rang/ordre) entre deux variables (*):

    - exemple avec $\rho \approx 1$: quand on prend les lignes qui sont dans le top/bottom 10 des $X$, pour ces mêmes lignes, on a également le top/bottom 10 des $Y$
    - exemple avec $\rho \approx -1$: quand on prend les lignes qui sont dans le top/bottom 10 des $X$, pour ces mêmes lignes, on a un ordre inversé : le top $\rightarrow$ bottom, et bottom $\rightarrow$ top
    - exemple avec $\rho \approx 0$: il n'y a pas de relation monotone, il n'y a pas d'ordre applicable pour chaque pair $(x_i,y_k)$
    - 
$\rho(X,Y) = \frac{\text{covar}(R(X),R(Y))}{\text{std}(R(X)) \cdot \text{std}(R(Y))} $  
avec $R(X) = \{R(x_i) | \forall x_i \in X \}$ le rang (ranking) et/ou ordre de la variable $X$  
$-1 \leq \rho(X,Y) \leq 1$

(*): plus exactement : si la relation décrit une fonction [monotone](https://en.wikipedia.org/wiki/Monotonic_function)

In [20]:
d1[["math","eng"]].corr(method='spearman')

          math       eng
math  1.000000 -0.385799
eng  -0.385799  1.000000