In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("data/Exercices_Pandas_athlete_events.csv")

In [6]:
"""22. Quels sont les joueurs ayant gagné des médailles d’Or en badminton simple au cours des
années. Trier le résultat par ordre alphabétique sur le nom des joueurs."""

cond_gold = data["Medal"] == "Gold"
cond_badminton_simple = (data["Event"].str.contains("single",case=False)) & (data["Sport"]=="Badminton")

print((cond_gold&cond_badminton_simple).sum())

(
    data
    .loc[cond_gold&cond_badminton_simple,:]
    .sort_values(by=["Name"],ascending=[True])
)

14

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
31409,16152,Alexander Alan Budikusuma Wiratama,M,24.0,178.0,71.0,Indonesia,INA,1992 Summer,1992,Summer,Barcelona,Badminton,Badminton Men's Singles,Gold
13855,7504,Bang Su-Hyeon,F,23.0,NaN,NaN,South Korea,KOR,1996 Summer,1996,Summer,Atlanta,Badminton,Badminton Women's Singles,Gold
149622,75045,Carolina Mara Marn Marn,F,23.0,172.0,65.0,Spain,ESP,2016 Summer,2016,Summer,Rio de Janeiro,Badminton,Badminton Women's Singles,Gold
39337,20238,Chen Long,M,27.0,188.0,81.0,China,CHN,2016 Summer,2016,Summer,Rio de Janeiro,Badminton,Badminton Men's Singles,Gold
81604,41427,Gong Zhichao,F,23.0,163.0,52.0,China,CHN,2000 Summer,2000,Summer,Sydney,Badminton,Badminton Women's Singles,Gold
108331,54755,Ji Xinpeng,M,22.0,181.0,70.0,China,CHN,2000 Summer,2000,Summer,Sydney,Badminton,Badminton Men's Singles,Gold
138456,69540,Li Xuerui,F,21.0,175.0,65.0,China,CHN,2012 Summer,2012,Summer,London,Badminton,Badminton Women's Singles,Gold
139311,69968,Lin Dan,M,24.0,177.0,70.0,China,CHN,2008 Summer,2008,Summer,Beijing,Badminton,Badminton Men's Singles,Gold
139312,69968,Lin Dan,M,28.0,177.0,70.0,China,CHN,2012 Summer,2012,Summer,London,Badminton,Badminton Men's Singles,Gold
232573,116659,"Lucia Francisca ""Susi"" Susanti Haditono",F,21.0,161.0,NaN,Indonesia,INA,1992 Summer,1992,Summer,Barcelona,Badminton,Badminton Women's Singles,Gold
99666,50431,Poul-Erik Hyer Larsen (-Engel Hyer),M,30.0,188.0,79.0,Denmark,DEN,1996 Summer,1996,Summer,Atlanta,Badminton,Badminton Men's Singles,Gold
95679,48435,Taufik Hidayat,M,23.0,175.0,65.0,Indonesia,INA,2004 Summer,2004,Summer,Athina,Badminton,Badminton Men's Singles,Gold
268880,134525,Zhang Ning,F,29.0,175.0,65.0,China,CHN,2004 Summer,2004,Summer,Athina,Badminton,Badminton Women's Singles,Gold
268881,134525,Zhang Ning,F,33.0,175.0,65.0,China,CHN,2008 Summer,2008,Summer,Beijing,Badminton,Badminton Women's Singles,Gold

In [15]:
"""32) Quels étaient les pays les plus efficaces durant la guerre froide de 1952 à 1988 (i.e. le pays
avec le plus de médailles par nombre d’athlètes envoyés)"""

cond_year= data["Year"].between(1952,1988, inclusive="both")
GB = (
    data
    .loc[cond_year,:]
    .groupby(["NOC"],as_index=0)
    .agg(count_medal = ("Medal","count"), count_athl=("ID","count"))
    .sort_values(by="count_medal",ascending=False)
)

GB["ratio"] = GB["count_medal"]/GB["count_athl"]
GB

     NOC  count_medal  count_athl     ratio
162  URS         2503        5685  0.440281
164  USA         1790        6244  0.286675
57   GDR         1005        2645  0.379962
70   HUN          616        2957  0.208319
53   FRG          586        3315  0.176772
..   ...          ...         ...       ...
165  VAN            0           6  0.000000
171  YAR            0          11  0.000000
169  VNM            0          62  0.000000
168  VIN            0           6  0.000000
172  YMD            0           5  0.000000

[176 rows x 4 columns]

In [17]:
GB2 = (
    data
    .drop_duplicates(subset=["NOC","Medal","Year","Event"])
    .loc[cond_year,:]
    .groupby(["NOC"],as_index=0)
    .agg(count_medal = ("Medal","count"), count_athl=("ID","count"))
    .sort_values(by="count_medal",ascending=False)
)
GB2["ratio"] = GB2["count_medal"]/GB2["count_athl"]
GB2.sort_values(by="ratio",ascending=0)

     NOC  count_medal  count_athl     ratio
162  URS         1197        2458  0.486981
57   GDR          519        1210  0.428926
164  USA          957        2486  0.384956
59   GER          168         719  0.233658
131  ROU          199         933  0.213290
..   ...          ...         ...       ...
165  VAN            0           6  0.000000
171  YAR            0          11  0.000000
169  VNM            0          38  0.000000
168  VIN            0           6  0.000000
172  YMD            0           5  0.000000

[176 rows x 4 columns]